allowBuilds:
  '@reown/appkit': true
  bufferutil: true
  keccak: true
  protobufjs: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  utf-8-validate: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
